---
layout: cv
title: Spencer Palmer's CV
---
# Spencer Palmer
Subcontractor, Software Engineer Student.

<div id="webaddress">
<a href="https://www.linkedin.com/in/spencer-palmer98/">Spencer Palmer - LinkedIn</a>
| <a href="https://github.com/Spalmer98">My Github page</a>
</div>


## Currently

A Senior at BrighamYoung University-Idaho, pursuing a bachelor’s degree in software engineering emphasizing in software design.

### Specialized in

Software design, Python, C#, 


### Research interests

Retail POS systems, other coding languages, changing the perspective of technicogical careers.


## Education

`January 2024 - Present`
__BrighamYoung University-Idaho, Rexburg__

- Junior, Senior

`2022-2023`
__Purdue Global University, Online.__

- Sophmore

`January 2020 - July 2020`
__BrighamYoung University-Idaho, Rexburg__

- Freshman

`September 2012 - June 1, 2016`
__Idaho Falls Senior High School, Idaho Falls__



## Awards

`2016`
Advanced Technological Honor Cord, *Idaho Falls Senior High School*, Idaho Falls, Idaho

`2016`
Leadership, Academic Excellence, and Service Honor Cord, *Technology Student Association*, Idaho, USA


## Cetifications

`September 2021 - Present` Forklift Operator Certification


## Occupation

`July 2025 - Present`
__SoundFX__, Idaho Falls, Idaho

- Subcontractor

`August 2024 - September 2024`
__Redstone Residential__, Rexburg, Idaho

- Temporary Maintenance Worker

`2023 - 2024`
__Big 5 Sporting Goods__, Ammon, Idaho

- Assistant Manager

`May 2022 - November 2022`
__Baker's Dozen__, Idaho Falls, Idaho

- Baker's Assistant

`2021 - 2022`
__Flood and Fire Solutions__, Idaho Falls, Idaho

- Restoration Technician

`2020 - 2021`
__Big Deal Outlet__, Idaho Falls, Idaho

- Front Store Manager

`2018 - 2019`
__Golden Valley Natural__, Shelly, Idaho

- Forklift Operator

`2016 - 2018`
__Johnson's Discount Foods__, Idaho Falls, Idaho

- Shift Supervisor


<!-- ### Footer

Last updated: July 2025 -->